#!/bin/sh

# Get rid of all the non-essential files.

set -x

rm -rf dist dist-deb build ,tmp MANIFEST
rm -f */*.pyc
rm -rf man/static-picture-publish.1* man/static-picture-publish.1.html
rm -f pod*.tmp
find . -type f -name  \*~ -print0 | xargs -0 rm -f
find . -type f -name .\*~ -print0 | xargs -0 rm -f

