#!/bin/sh

# Create the python module distribution.  This must be run from within
# the static-picture-publish source directory.

set -e -x

# Check for things that indicat we are in the static-picture-publish source
# directory.
[ -f VERSION ]
[ -f setup.py ]
[ -d static_picture_publish ]
[ -d xsl ]

_VERSION="$(head -1 VERSION)"

set +e
Changes="$( tla changes > /dev/null ; echo $? )"
set -e

case $Changes in
  0) Modified=""    ; break ;;
  1) Modified=" (Modified)" ; break ;;
  *)
    echo Error from '`tla changes`' 1>&2
    exit $Changes
    break ;;
esac

TlaVersion=$(tla tree-version)--$(tla logs | tail -1)"$Modified"

./make-man

rm -rf dist build

python setup.py sdist
python setup.py bdist

# RPM building is broken, it looks for static-picture-publish.1 where there is a
# static-picture-publish.1.gz.
# Fixed the man page problem, now it won't build when I include the embedded
# EPS pages.

#python setup.py bdist_rpm

# arch-tag: 0aa21380-e56a-4814-b64f-836aee8221cf
