#!/bin/bash

# Make the static-picture-publish man page.


pod2man  --center="User Commands" \
         --release="User Commands" \
         man/static-picture-publish.pod \
         man/static-picture-publish.1

man -t man/static-picture-publish.1 > man/static-picture-publish.1.ps

pod2html --header \
         --infile=man/static-picture-publish.pod \
         --outfile=man/static-picture-publish.1.html

gzip -c man/static-picture-publish.1 > man/static-picture-publish.1.gz

# arch-tag: 14f661c3-3082-4200-a5de-2dba3a8c4327
