#!/bin/sh

# Make the debian package.  This must be run from within the source
# directory.

set -e -x

# Check for things that indicate we are in the makediary source
# directory.
[ -f VERSION ]
[ -f setup.py ]
[ -d static_picture_publish ]
[ -d css ]
[ -d xsl ]
[ -d xslt-examples ]

_VERSION="$(head -1 VERSION)"

_SRC_DIR="$(pwd)"
_DEB_BUILD_DIR=$_SRC_DIR/,tmp/deb/static-picture-publish-$_VERSION

rm -rf $_DEB_BUILD_DIR
mkdir -p $_DEB_BUILD_DIR

# Here, we assume that the source tree does not contain any files whose names
# will be escaped by tla.
tla inventory -s \
   | tar cf - -T - \
   | ( cd $_DEB_BUILD_DIR  &&  tar xvf - )

cd $_DEB_BUILD_DIR
./make-man

fakeroot dpkg-buildpackage -uc -us

cd $_SRC_DIR
mkdir -p dist-deb
cp -pv $_SRC_DIR/,tmp/deb/static-picture-publish* dist-deb/

# arch-tag: 85c8f6d7-bb19-45ac-ae1f-44c0b85b9219
